spring:
  config:
    import: application-secret.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB  # 파일의 최대 크기
      max-request-size: 10MB  # 요청의 최대 크기 (여러 파일을 포함할 수 있음)